/*Copyright (c) 2017-2018 ixiacom.com All Rights Reserved.
 This software is the confidential and proprietary information of ixiacom.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with ixiacom.com*/
package com.ixtest20.new_ixtest_20;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bugstatus generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`BUGSTATUS`")
public class Bugstatus implements Serializable {

    private Integer statusid;
    private String bugstatus;

    @Id
    @Column(name = "`STATUSID`", nullable = false, scale = 0, precision = 10)
    public Integer getStatusid() {
        return this.statusid;
    }

    public void setStatusid(Integer statusid) {
        this.statusid = statusid;
    }

    @Column(name = "`BUGSTATUS`", nullable = true, length = 64)
    public String getBugstatus() {
        return this.bugstatus;
    }

    public void setBugstatus(String bugstatus) {
        this.bugstatus = bugstatus;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Bugstatus)) return false;
        final Bugstatus bugstatusInstance = (Bugstatus) o;
        return Objects.equals(getStatusid(), bugstatusInstance.getStatusid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStatusid());
    }
}

