/*Copyright (c) 2017-2018 ixiacom.com All Rights Reserved.
 This software is the confidential and proprietary information of ixiacom.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with ixiacom.com*/
package com.ixtest20.new_ixtest_20;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

/**
 * Bugtable generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`BUGTABLE`")
public class Bugtable implements Serializable {

    private BigInteger bugid;
    private BigInteger status;
    private BigInteger assignedto;
    @Type(type = "DateTime")
    private LocalDateTime lastmodified;
    private BigInteger buildnumber;

    @Id
    @Column(name = "`BUGID`", nullable = false, scale = 0, precision = 19)
    public BigInteger getBugid() {
        return this.bugid;
    }

    public void setBugid(BigInteger bugid) {
        this.bugid = bugid;
    }

    @Column(name = "`STATUS`", nullable = true, scale = 0, precision = 19)
    public BigInteger getStatus() {
        return this.status;
    }

    public void setStatus(BigInteger status) {
        this.status = status;
    }

    @Column(name = "`ASSIGNEDTO`", nullable = true, scale = 0, precision = 19)
    public BigInteger getAssignedto() {
        return this.assignedto;
    }

    public void setAssignedto(BigInteger assignedto) {
        this.assignedto = assignedto;
    }

    @Column(name = "`LASTMODIFIED`", nullable = true)
    public LocalDateTime getLastmodified() {
        return this.lastmodified;
    }

    public void setLastmodified(LocalDateTime lastmodified) {
        this.lastmodified = lastmodified;
    }

    @Column(name = "`BUILDNUMBER`", nullable = true, scale = 0, precision = 19)
    public BigInteger getBuildnumber() {
        return this.buildnumber;
    }

    public void setBuildnumber(BigInteger buildnumber) {
        this.buildnumber = buildnumber;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Bugtable)) return false;
        final Bugtable bugtable = (Bugtable) o;
        return Objects.equals(getBugid(), bugtable.getBugid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getBugid());
    }
}

