/*Copyright (c) 2017-2018 ixiacom.com All Rights Reserved.
 This software is the confidential and proprietary information of ixiacom.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with ixiacom.com*/
package com.ixtest20.new_ixtest_20;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

/**
 * DeletedBuild generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`DELETED_BUILD`")
public class DeletedBuild implements Serializable {

    private BigDecimal idDeletedBuild;
    private BigDecimal buildId;
    private String buildNumber;
    private BigDecimal associatedApp;
    private BigDecimal productId;
    @Type(type = "DateTime")
    private LocalDateTime buildDate;
    private String path;

    @Id
    @Column(name = "`ID_DELETED_BUILD`", nullable = false, scale = 9, precision = 22)
    public BigDecimal getIdDeletedBuild() {
        return this.idDeletedBuild;
    }

    public void setIdDeletedBuild(BigDecimal idDeletedBuild) {
        this.idDeletedBuild = idDeletedBuild;
    }

    @Column(name = "`BUILD_ID`", nullable = true, scale = 9, precision = 22)
    public BigDecimal getBuildId() {
        return this.buildId;
    }

    public void setBuildId(BigDecimal buildId) {
        this.buildId = buildId;
    }

    @Column(name = "`BUILD_NUMBER`", nullable = true, length = 32)
    public String getBuildNumber() {
        return this.buildNumber;
    }

    public void setBuildNumber(String buildNumber) {
        this.buildNumber = buildNumber;
    }

    @Column(name = "`ASSOCIATED_APP`", nullable = true, scale = 9, precision = 22)
    public BigDecimal getAssociatedApp() {
        return this.associatedApp;
    }

    public void setAssociatedApp(BigDecimal associatedApp) {
        this.associatedApp = associatedApp;
    }

    @Column(name = "`PRODUCT_ID`", nullable = true, scale = 9, precision = 22)
    public BigDecimal getProductId() {
        return this.productId;
    }

    public void setProductId(BigDecimal productId) {
        this.productId = productId;
    }

    @Column(name = "`BUILD_DATE`", nullable = true)
    public LocalDateTime getBuildDate() {
        return this.buildDate;
    }

    public void setBuildDate(LocalDateTime buildDate) {
        this.buildDate = buildDate;
    }

    @Column(name = "`PATH`", nullable = true, length = 64)
    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DeletedBuild)) return false;
        final DeletedBuild deletedBuild = (DeletedBuild) o;
        return Objects.equals(getIdDeletedBuild(), deletedBuild.getIdDeletedBuild());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIdDeletedBuild());
    }
}

