/*Copyright (c) 2017-2018 ixiacom.com All Rights Reserved.
 This software is the confidential and proprietary information of ixiacom.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with ixiacom.com*/
package com.ixtest20.new_ixtest_20;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EnginesBack97 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ENGINES_BACK_9_7`")
public class EnginesBack97 implements Serializable {

    private BigInteger engineid;
    private String enginename;
    private BigInteger productid;
    private BigInteger buildid;
    private BigInteger noOfTestcases;
    private BigInteger iopSuiteId;
    private BigInteger ixtestplanid;
    private BigInteger ixtestplancount;

    @Id
    @Column(name = "`ENGINEID`", nullable = false, scale = 0, precision = 19)
    public BigInteger getEngineid() {
        return this.engineid;
    }

    public void setEngineid(BigInteger engineid) {
        this.engineid = engineid;
    }

    @Column(name = "`ENGINENAME`", nullable = true, length = 128)
    public String getEnginename() {
        return this.enginename;
    }

    public void setEnginename(String enginename) {
        this.enginename = enginename;
    }

    @Column(name = "`PRODUCTID`", nullable = true, scale = 0, precision = 19)
    public BigInteger getProductid() {
        return this.productid;
    }

    public void setProductid(BigInteger productid) {
        this.productid = productid;
    }

    @Column(name = "`BUILDID`", nullable = true, scale = 0, precision = 19)
    public BigInteger getBuildid() {
        return this.buildid;
    }

    public void setBuildid(BigInteger buildid) {
        this.buildid = buildid;
    }

    @Column(name = "`NO_OF_TESTCASES`", nullable = true, scale = 0, precision = 19)
    public BigInteger getNoOfTestcases() {
        return this.noOfTestcases;
    }

    public void setNoOfTestcases(BigInteger noOfTestcases) {
        this.noOfTestcases = noOfTestcases;
    }

    @Column(name = "`IOP_SUITE_ID`", nullable = true, scale = 0, precision = 19)
    public BigInteger getIopSuiteId() {
        return this.iopSuiteId;
    }

    public void setIopSuiteId(BigInteger iopSuiteId) {
        this.iopSuiteId = iopSuiteId;
    }

    @Column(name = "`IXTESTPLANID`", nullable = true, scale = 0, precision = 19)
    public BigInteger getIxtestplanid() {
        return this.ixtestplanid;
    }

    public void setIxtestplanid(BigInteger ixtestplanid) {
        this.ixtestplanid = ixtestplanid;
    }

    @Column(name = "`IXTESTPLANCOUNT`", nullable = true, scale = 0, precision = 19)
    public BigInteger getIxtestplancount() {
        return this.ixtestplancount;
    }

    public void setIxtestplancount(BigInteger ixtestplancount) {
        this.ixtestplancount = ixtestplancount;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EnginesBack97)) return false;
        final EnginesBack97 enginesBack97 = (EnginesBack97) o;
        return Objects.equals(getEngineid(), enginesBack97.getEngineid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEngineid());
    }
}

