/*Copyright (c) 2017-2018 ixiacom.com All Rights Reserved.
 This software is the confidential and proprietary information of ixiacom.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with ixiacom.com*/
package com.ixtest20.new_ixtest_20;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PBugtableRun generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`P_BUGTABLE_RUN`")
public class PBugtableRun implements Serializable {

    private BigInteger id;
    private BigInteger bugid;
    private BigInteger runid;
    private BigDecimal invalid;
    private Bugtable bugtable;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 19)
    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    @Column(name = "`BUGID`", nullable = true, scale = 0, precision = 19)
    public BigInteger getBugid() {
        return this.bugid;
    }

    public void setBugid(BigInteger bugid) {
        this.bugid = bugid;
    }

    @Column(name = "`RUNID`", nullable = true, scale = 0, precision = 19)
    public BigInteger getRunid() {
        return this.runid;
    }

    public void setRunid(BigInteger runid) {
        this.runid = runid;
    }

    @Column(name = "`INVALID`", nullable = true, scale = 9, precision = 22)
    public BigDecimal getInvalid() {
        return this.invalid;
    }

    public void setInvalid(BigDecimal invalid) {
        this.invalid = invalid;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`BUGID`", referencedColumnName = "`BUGID`", insertable = false, updatable = false)
    public Bugtable getBugtable() {
        return this.bugtable;
    }

    public void setBugtable(Bugtable bugtable) {
        if(bugtable != null) {
            this.bugid = bugtable.getBugid();
        }

        this.bugtable = bugtable;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PBugtableRun)) return false;
        final PBugtableRun pbugtableRun = (PBugtableRun) o;
        return Objects.equals(getId(), pbugtableRun.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

