/*Copyright (c) 2017-2018 ixiacom.com All Rights Reserved.
 This software is the confidential and proprietary information of ixiacom.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with ixiacom.com*/
package com.ixtest20.new_ixtest_20;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PNetworkRun generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`P_NETWORK_RUN`")
public class PNetworkRun implements Serializable {

    private BigInteger id;
    private BigInteger testconfigid;
    private BigInteger runid;
    private BigDecimal invalid;
    private Testcaserun testcaserun;
    private Network network;

    @Id
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 19)
    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    @Column(name = "`TESTCONFIGID`", nullable = true, scale = 0, precision = 19)
    public BigInteger getTestconfigid() {
        return this.testconfigid;
    }

    public void setTestconfigid(BigInteger testconfigid) {
        this.testconfigid = testconfigid;
    }

    @Column(name = "`RUNID`", nullable = true, scale = 0, precision = 19)
    public BigInteger getRunid() {
        return this.runid;
    }

    public void setRunid(BigInteger runid) {
        this.runid = runid;
    }

    @Column(name = "`INVALID`", nullable = true, scale = 9, precision = 22)
    public BigDecimal getInvalid() {
        return this.invalid;
    }

    public void setInvalid(BigDecimal invalid) {
        this.invalid = invalid;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`RUNID`", referencedColumnName = "`TESTCASERUNID`", insertable = false, updatable = false)
    public Testcaserun getTestcaserun() {
        return this.testcaserun;
    }

    public void setTestcaserun(Testcaserun testcaserun) {
        if(testcaserun != null) {
            this.runid = testcaserun.getTestcaserunid();
        }

        this.testcaserun = testcaserun;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`TESTCONFIGID`", referencedColumnName = "`NETWORKID`", insertable = false, updatable = false)
    public Network getNetwork() {
        return this.network;
    }

    public void setNetwork(Network network) {
        if(network != null) {
            this.testconfigid = network.getNetworkid();
        }

        this.network = network;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PNetworkRun)) return false;
        final PNetworkRun pnetworkRun = (PNetworkRun) o;
        return Objects.equals(getId(), pnetworkRun.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

