/*Copyright (c) 2017-2018 ixiacom.com All Rights Reserved.
 This software is the confidential and proprietary information of ixiacom.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with ixiacom.com*/
package com.ixtest20.new_ixtest_20;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * Products generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`PRODUCTS`")
public class Products implements Serializable {

    private BigInteger productid;
    private String productname;
    private BigInteger status;
    private BigInteger ixtrackerid;
    private List<Builds> buildses = new ArrayList<>();
    private List<Engines> engineses = new ArrayList<>();
    private List<IopBuildApps> iopBuildAppses = new ArrayList<>();
    private List<IopEnginesDetails> iopEnginesDetailses = new ArrayList<>();
    private List<Releases> releaseses = new ArrayList<>();
    private List<Testcaserun> testcaseruns = new ArrayList<>();
    private List<Testcases> testcaseses = new ArrayList<>();
    private List<Testplan> testplans = new ArrayList<>();

    @Id
    @Column(name = "`PRODUCTID`", nullable = false, scale = 0, precision = 19)
    public BigInteger getProductid() {
        return this.productid;
    }

    public void setProductid(BigInteger productid) {
        this.productid = productid;
    }

    @Column(name = "`PRODUCTNAME`", nullable = true, length = 32)
    public String getProductname() {
        return this.productname;
    }

    public void setProductname(String productname) {
        this.productname = productname;
    }

    @Column(name = "`STATUS`", nullable = false, scale = 0, precision = 19)
    public BigInteger getStatus() {
        return this.status;
    }

    public void setStatus(BigInteger status) {
        this.status = status;
    }

    @Column(name = "`IXTRACKERID`", nullable = true, scale = 0, precision = 19)
    public BigInteger getIxtrackerid() {
        return this.ixtrackerid;
    }

    public void setIxtrackerid(BigInteger ixtrackerid) {
        this.ixtrackerid = ixtrackerid;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "products")
    public List<Builds> getBuildses() {
        return this.buildses;
    }

    public void setBuildses(List<Builds> buildses) {
        this.buildses = buildses;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "products")
    public List<Engines> getEngineses() {
        return this.engineses;
    }

    public void setEngineses(List<Engines> engineses) {
        this.engineses = engineses;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "products")
    public List<IopBuildApps> getIopBuildAppses() {
        return this.iopBuildAppses;
    }

    public void setIopBuildAppses(List<IopBuildApps> iopBuildAppses) {
        this.iopBuildAppses = iopBuildAppses;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "products")
    public List<IopEnginesDetails> getIopEnginesDetailses() {
        return this.iopEnginesDetailses;
    }

    public void setIopEnginesDetailses(List<IopEnginesDetails> iopEnginesDetailses) {
        this.iopEnginesDetailses = iopEnginesDetailses;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "products")
    public List<Releases> getReleaseses() {
        return this.releaseses;
    }

    public void setReleaseses(List<Releases> releaseses) {
        this.releaseses = releaseses;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "products")
    public List<Testcaserun> getTestcaseruns() {
        return this.testcaseruns;
    }

    public void setTestcaseruns(List<Testcaserun> testcaseruns) {
        this.testcaseruns = testcaseruns;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "products")
    public List<Testcases> getTestcaseses() {
        return this.testcaseses;
    }

    public void setTestcaseses(List<Testcases> testcaseses) {
        this.testcaseses = testcaseses;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "products")
    public List<Testplan> getTestplans() {
        return this.testplans;
    }

    public void setTestplans(List<Testplan> testplans) {
        this.testplans = testplans;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Products)) return false;
        final Products products = (Products) o;
        return Objects.equals(getProductid(), products.getProductid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getProductid());
    }
}

