/*Copyright (c) 2017-2018 ixiacom.com All Rights Reserved.
 This software is the confidential and proprietary information of ixiacom.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with ixiacom.com*/
package com.ixtest20.new_ixtest_20;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * Testcaserun generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TESTCASERUN`")
public class Testcaserun implements Serializable {

    private BigInteger testcaserunid;
    @Type(type = "DateTime")
    private LocalDateTime startDate;
    @Type(type = "DateTime")
    private LocalDateTime endDate;
    private String config;
    private String logfilelink;
    private String description;
    private String preCon;
    private String comments;
    private String target;
    private String obtained;
    private BigInteger engineid;
    private BigInteger testcaseid;
    private BigInteger buildid;
    private BigInteger productid;
    private Integer resultid;
    private BigInteger iopSuiteId;
    private BigDecimal invalid;
    private String cardSerialNumber;
    private Engines engines;
    private Testcases testcases;
    private Products products;
    private Builds builds;
    private List<PDutRun> pdutRuns = new ArrayList<>();
    private List<PNetworkRun> pnetworkRuns = new ArrayList<>();

    @Id
    @Column(name = "`TESTCASERUNID`", nullable = false, scale = 0, precision = 19)
    public BigInteger getTestcaserunid() {
        return this.testcaserunid;
    }

    public void setTestcaserunid(BigInteger testcaserunid) {
        this.testcaserunid = testcaserunid;
    }

    @Column(name = "`START_DATE`", nullable = true)
    public LocalDateTime getStartDate() {
        return this.startDate;
    }

    public void setStartDate(LocalDateTime startDate) {
        this.startDate = startDate;
    }

    @Column(name = "`END_DATE`", nullable = true)
    public LocalDateTime getEndDate() {
        return this.endDate;
    }

    public void setEndDate(LocalDateTime endDate) {
        this.endDate = endDate;
    }

    @Column(name = "`CONFIG`", nullable = true, length = 255)
    public String getConfig() {
        return this.config;
    }

    public void setConfig(String config) {
        this.config = config;
    }

    @Column(name = "`LOGFILELINK`", nullable = true, length = 255)
    public String getLogfilelink() {
        return this.logfilelink;
    }

    public void setLogfilelink(String logfilelink) {
        this.logfilelink = logfilelink;
    }

    @Column(name = "`DESCRIPTION`", nullable = true, length = 2048)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "`PRE_CON`", nullable = true, length = 1024)
    public String getPreCon() {
        return this.preCon;
    }

    public void setPreCon(String preCon) {
        this.preCon = preCon;
    }

    @Column(name = "`COMMENTS`", nullable = true, length = 4000)
    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    @Column(name = "`TARGET`", nullable = true, length = 255)
    public String getTarget() {
        return this.target;
    }

    public void setTarget(String target) {
        this.target = target;
    }

    @Column(name = "`OBTAINED`", nullable = true, length = 255)
    public String getObtained() {
        return this.obtained;
    }

    public void setObtained(String obtained) {
        this.obtained = obtained;
    }

    @Column(name = "`ENGINEID`", nullable = true, scale = 0, precision = 19)
    public BigInteger getEngineid() {
        return this.engineid;
    }

    public void setEngineid(BigInteger engineid) {
        this.engineid = engineid;
    }

    @Column(name = "`TESTCASEID`", nullable = true, scale = 0, precision = 19)
    public BigInteger getTestcaseid() {
        return this.testcaseid;
    }

    public void setTestcaseid(BigInteger testcaseid) {
        this.testcaseid = testcaseid;
    }

    @Column(name = "`BUILDID`", nullable = true, scale = 0, precision = 19)
    public BigInteger getBuildid() {
        return this.buildid;
    }

    public void setBuildid(BigInteger buildid) {
        this.buildid = buildid;
    }

    @Column(name = "`PRODUCTID`", nullable = true, scale = 0, precision = 19)
    public BigInteger getProductid() {
        return this.productid;
    }

    public void setProductid(BigInteger productid) {
        this.productid = productid;
    }

    @Column(name = "`RESULTID`", nullable = true, scale = 0, precision = 10)
    public Integer getResultid() {
        return this.resultid;
    }

    public void setResultid(Integer resultid) {
        this.resultid = resultid;
    }

    @Column(name = "`IOP_SUITE_ID`", nullable = true, scale = 0, precision = 19)
    public BigInteger getIopSuiteId() {
        return this.iopSuiteId;
    }

    public void setIopSuiteId(BigInteger iopSuiteId) {
        this.iopSuiteId = iopSuiteId;
    }

    @Column(name = "`INVALID`", nullable = true, scale = 9, precision = 22)
    public BigDecimal getInvalid() {
        return this.invalid;
    }

    public void setInvalid(BigDecimal invalid) {
        this.invalid = invalid;
    }

    @Column(name = "`CARD_SERIAL_NUMBER`", nullable = true, length = 256)
    public String getCardSerialNumber() {
        return this.cardSerialNumber;
    }

    public void setCardSerialNumber(String cardSerialNumber) {
        this.cardSerialNumber = cardSerialNumber;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`ENGINEID`", referencedColumnName = "`ENGINEID`", insertable = false, updatable = false)
    public Engines getEngines() {
        return this.engines;
    }

    public void setEngines(Engines engines) {
        if(engines != null) {
            this.engineid = engines.getEngineid();
        }

        this.engines = engines;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`TESTCASEID`", referencedColumnName = "`TESTCASEID`", insertable = false, updatable = false)
    public Testcases getTestcases() {
        return this.testcases;
    }

    public void setTestcases(Testcases testcases) {
        if(testcases != null) {
            this.testcaseid = testcases.getTestcaseid();
        }

        this.testcases = testcases;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`PRODUCTID`", referencedColumnName = "`PRODUCTID`", insertable = false, updatable = false)
    public Products getProducts() {
        return this.products;
    }

    public void setProducts(Products products) {
        if(products != null) {
            this.productid = products.getProductid();
        }

        this.products = products;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`BUILDID`", referencedColumnName = "`BUILDID`", insertable = false, updatable = false)
    public Builds getBuilds() {
        return this.builds;
    }

    public void setBuilds(Builds builds) {
        if(builds != null) {
            this.buildid = builds.getBuildid();
        }

        this.builds = builds;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "testcaserun")
    public List<PDutRun> getPdutRuns() {
        return this.pdutRuns;
    }

    public void setPdutRuns(List<PDutRun> pdutRuns) {
        this.pdutRuns = pdutRuns;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "testcaserun")
    public List<PNetworkRun> getPnetworkRuns() {
        return this.pnetworkRuns;
    }

    public void setPnetworkRuns(List<PNetworkRun> pnetworkRuns) {
        this.pnetworkRuns = pnetworkRuns;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Testcaserun)) return false;
        final Testcaserun testcaserun = (Testcaserun) o;
        return Objects.equals(getTestcaserunid(), testcaserun.getTestcaserunid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTestcaserunid());
    }
}

